<?php

namespace Kanekescom\Siasn\Simpeg\Transformers;

use Kanekescom\Siasn\Simpeg\Models\DataUtama;
use League\Fractal\TransformerAbstract;

class DataUtamaTransformer extends TransformerAbstract
{
    /**
     * Transform the DataUtama model.
     *
     * @param  Kanekescom\Siasn\Simpeg\Models\DataUtama  $model
     */
    public function transform(DataUtama $model): array
    {
        return [
            'id' => $model->id,

            /* place your other model properties here */
            'nip_baru' => $model->nip_baru,
            'nip_lama' => $model->nip_lama,
            'nama' => $model->nama,
            'gelar_depan' => $model->gelar_depan,
            'gelar_belakang' => $model->gelar_belakang,
            'tempat_lahir' => $model->tempat_lahir,
            'tempat_lahir_id' => $model->tempat_lahir_id,
            'tgl_lahir' => $model->tgl_lahir,
            'agama' => $model->agama,
            'agama_id' => $model->agama_id,
            'email' => $model->email,
            'email_gov' => $model->email_gov,
            'nik' => $model->nik,
            'alamat' => $model->alamat,
            'no_hp' => $model->no_hp,
            'no_telp' => $model->no_telp,
            'jenis_pegawai_id' => $model->jenis_pegawai_id,
            'mk_tahun' => $model->mk_tahun,
            'mk_bulan' => $model->mk_bulan,
            'jenis_pegawai_nama' => $model->jenis_pegawai_nama,
            'kedudukan_pns_id' => $model->kedudukan_pns_id,
            'kedudukan_pns_nama' => $model->kedudukan_pns_nama,
            'status_pegawai' => $model->status_pegawai,
            'jenis_kelamin' => $model->jenis_kelamin,
            'jenis_id_dokumen_id' => $model->jenis_id_dokumen_id,
            'jenis_id_dokumen_nama' => $model->jenis_id_dokumen_nama,
            'nomor_id_document' => $model->nomor_id_document,
            'no_seri_karpeg' => $model->no_seri_karpeg,
            'tk_pendidikan_terakhir_id' => $model->tk_pendidikan_terakhir_id,
            'tk_pendidikan_terakhir' => $model->tk_pendidikan_terakhir,
            'pendidikan_terakhir_id' => $model->pendidikan_terakhir_id,
            'pendidikan_terakhir_nama' => $model->pendidikan_terakhir_nama,
            'tahun_lulus' => $model->tahun_lulus,
            'tmt_pns' => $model->tmt_pns,
            'tmt_pensiun' => $model->tmt_pensiun,
            'bup_pensiun' => $model->bup_pensiun,
            'tgl_sk_pns' => $model->tgl_sk_pns,
            'tmt_cpns' => $model->tmt_cpns,
            'tgl_sk_cpns' => $model->tgl_sk_cpns,
            'instansi_induk_id' => $model->instansi_induk_id,
            'instansi_induk_nama' => $model->instansi_induk_nama,
            'satuan_kerja_induk_id' => $model->satuan_kerja_induk_id,
            'satuan_kerja_induk_nama' => $model->satuan_kerja_induk_nama,
            'kanreg_id' => $model->kanreg_id,
            'kanreg_nama' => $model->kanreg_nama,
            'instansi_kerja_id' => $model->instansi_kerja_id,
            'instansi_kerja_nama' => $model->instansi_kerja_nama,
            'instansi_kerja_kode_cepat' => $model->instansi_kerja_kode_cepat,
            'satuan_kerja_kerja_id' => $model->satuan_kerja_kerja_id,
            'satuan_kerja_kerja_nama' => $model->satuan_kerja_kerja_nama,
            'unor_id' => $model->unor_id,
            'unor_nama' => $model->unor_nama,
            'unor_induk_id' => $model->unor_induk_id,
            'unor_induk_nama' => $model->unor_induk_nama,
            'jenis_jabatan_id' => $model->jenis_jabatan_id,
            'jenis_jabatan' => $model->jenis_jabatan,
            'jabatan_nama' => $model->jabatan_nama,
            'jabatan_struktural_id' => $model->jabatan_struktural_id,
            'jabatan_struktural_nama' => $model->jabatan_struktural_nama,
            'jabatan_fungsional_id' => $model->jabatan_fungsional_id,
            'jabatan_fungsional_nama' => $model->jabatan_fungsional_nama,
            'jabatan_fungsional_umum_id' => $model->jabatan_fungsional_umum_id,
            'jabatan_fungsional_umum_nama' => $model->jabatan_fungsional_umum_nama,
            'tmt_jabatan' => $model->tmt_jabatan,
            'lokasi_kerja_id' => $model->lokasi_kerja_id,
            'lokasi_kerja' => $model->lokasi_kerja,
            'gol_ruang_awal_id' => $model->gol_ruang_awal_id,
            'gol_ruang_awal' => $model->gol_ruang_awal,
            'gol_ruang_akhir_id' => $model->gol_ruang_akhir_id,
            'gol_ruang_akhir' => $model->gol_ruang_akhir,
            'tmt_gol_akhir' => $model->tmt_gol_akhir,
            'masa_kerja' => $model->masa_kerja,
            'eselon' => $model->eselon,
            'eselon_id' => $model->eselon_id,
            'eselon_level' => $model->eselon_level,
            'tmt_eselon' => $model->tmt_eselon,
            'gaji_pokok' => $model->gaji_pokok,
            'kpkn_id' => $model->kpkn_id,
            'kpkn_nama' => $model->kpkn_nama,
            'ktua_id' => $model->ktua_id,
            'ktua_nama' => $model->ktua_nama,
            'taspen_id' => $model->taspen_id,
            'taspen_nama' => $model->taspen_nama,
            'jenis_kawin_id' => $model->jenis_kawin_id,
            'status_perkawinan' => $model->status_perkawinan,
            'status_hidup' => $model->status_hidup,
            'tgl_surat_keterangan_dokter' => $model->tgl_surat_keterangan_dokter,
            'no_surat_keterangan_dokter' => $model->no_surat_keterangan_dokter,
            'jumlah_istri_suami' => $model->jumlah_istri_suami,
            'jumlah_anak' => $model->jumlah_anak,
            'no_surat_keterangan_bebas_narkoba' => $model->no_surat_keterangan_bebas_narkoba,
            'tgl_surat_keterangan_bebas_narkoba' => $model->tgl_surat_keterangan_bebas_narkoba,
            'skck' => $model->skck,
            'tgl_skck' => $model->tgl_skck,
            'akte_kelahiran' => $model->akte_kelahiran,
            'akte_meninggal' => $model->akte_meninggal,
            'tgl_meninggal' => $model->tgl_meninggal,
            'no_npwp' => $model->no_npwp,
            'tgl_npwp' => $model->tgl_npwp,
            'no_askes' => $model->no_askes,
            'bpjs' => $model->bpjs,
            'kode_pos' => $model->kode_pos,
            'no_spmt' => $model->no_spmt,
            'no_taspen' => $model->no_taspen,
            'bahasa' => $model->bahasa,
            'kppn_id' => $model->kppn_id,
            'kppn_nama' => $model->kppn_nama,
            'pangkat_akhir' => $model->pangkat_akhir,
            'tgl_sttpl' => $model->tgl_sttpl,
            'nomor_sttpl' => $model->nomor_sttpl,
            'nomor_sk_cpns' => $model->nomor_sk_cpns,
            'nomor_sk_pns' => $model->nomor_sk_pns,
            'jenjang' => $model->jenjang,
            'jabatan_asn' => $model->jabatan_asn,
            'kartu_asn' => $model->kartu_asn,

            // 'created_at' => $model->created_at,
            // 'updated_at' => $model->updated_at,
            // 'deleted_at' => $model->deleted_at,
        ];
    }
}
